version: '3.1'

services:

# image wordpress
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
# Docker secrets!!!
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
###################
    volumes:
      - wordpress:/var/www/html

  database:
    image: mysql:5.7
    restart: always
# Docker secrets!!!
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
###################
    volumes:
      - database:/var/lib/mysql

volumes:
  wordpress:
  database:
