version: '3.1'

services:

# image wordpress
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: database 
      WORDPRESS_DB_USER_FILE: /run/secrets/db_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME_FILE: /run/secrets/db_name
    secrets:
      - db_user
      - db_password
      - db_name

    volumes:
      - wordpress:/var/www/html

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE_FILE: /run/secrets/db_name
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    secrets:
      - db_user
      - db_password
      - db_name

    volumes:
      - database:/var/lib/mysql

secrets:
  db_user:
      external: true
  db_password:
      external: true
  db_name:
      external: true
    
volumes:
  wordpress:
  database:

